name: HostGator Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.85.0'
    - name: Deploy to HostGator
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOSTGATOR_HOST }}
        username: ${{ secrets.HOSTGATOR_USERNAME }}
        password: ${{ secrets.HOSTGATOR_PASSWORD }}
        script: |
          cd public_html
          rm -rf *
          cp -r /github/workspace/public/* .
